#!/bin/bash

# Step 13: Demo Runs & Artifacts Collection
# ==========================================
# This script demonstrates RepoArchitectAgent by analyzing sample repositories
# and collecting all artifacts (analysis, diagrams, summaries, CI templates)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEMO_DIR="$PROJECT_ROOT/demo/runs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RUN_DIR="$DEMO_DIR/$TIMESTAMP"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function: Print colored output
log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }

# Function: Run analysis on a repo
run_analysis() {
    local repo_url=$1
    local repo_name=$(echo "$repo_url" | awk -F'/' '{print $(NF-1)"_"$NF}' | sed 's/.git$//')
    local output_dir="$RUN_DIR/$repo_name"
    
    mkdir -p "$output_dir"
    
    log_info "Analyzing: $repo_url"
    log_info "Output: $output_dir"
    
    # Step 1: Analyze repository structure
    log_info "Step 1/4: Analyzing repository structure..."
    if python "$PROJECT_ROOT/api/analyze_repo.py" "$repo_url" > "$output_dir/analysis.json" 2>&1; then
        log_success "Repository structure analyzed"
        # Show summary
        if command -v jq &> /dev/null; then
            echo "  Languages: $(jq -r '.languages | keys | join(", ")' "$output_dir/analysis.json" 2>/dev/null || echo 'unknown')"
            echo "  Frameworks: $(jq -r '.frameworks | keys | join(", ")' "$output_dir/analysis.json" 2>/dev/null || echo 'unknown')"
        fi
    else
        log_error "Repository analysis failed"
        echo "  Check: $output_dir/analysis.json"
        return 1
    fi
    
    # Step 2: Generate diagram
    log_info "Step 2/4: Generating architecture diagram..."
    if node "$PROJECT_ROOT/api/generate_mermaid.js" < "$output_dir/analysis.json" > "$output_dir/diagram.mmd" 2>&1; then
        log_success "Architecture diagram generated"
        echo "  Size: $(wc -l < "$output_dir/diagram.mmd") lines"
    else
        log_warn "Diagram generation skipped (non-critical)"
        echo "  Diagram not available for this repository"
    fi
    
    # Step 3: Generate AI summary
    log_info "Step 3/4: Generating AI summary..."
    if node "$PROJECT_ROOT/api/generate_summary.js" < "$output_dir/analysis.json" > "$output_dir/summary.json" 2>&1; then
        log_success "AI summary generated"
        if command -v jq &> /dev/null; then
            echo "  Summary: $(jq -r '.summary' "$output_dir/summary.json" 2>/dev/null | head -c 80)..."
        fi
    else
        log_warn "AI summary skipped (API key not configured)"
        echo "  Set OUMI_API_KEY or OPENAI_API_KEY to enable"
    fi
    
    # Step 4: Generate CI template
    log_info "Step 4/4: Generating CI/CD template..."
    if node "$PROJECT_ROOT/api/generate_ci.js" < "$output_dir/analysis.json" > "$output_dir/ci_template.yml" 2>&1; then
        log_success "CI/CD template generated"
        echo "  Size: $(wc -l < "$output_dir/ci_template.yml") lines"
    else
        log_warn "CI template generation skipped"
    fi
    
    # Step 5: Create combined report
    log_info "Creating combined report..."
    create_report "$output_dir" "$repo_url" "$repo_name"
    
    log_success "Demo complete for: $repo_name"
    echo ""
}

# Function: Create combined report
create_report() {
    local output_dir=$1
    local repo_url=$2
    local repo_name=$3
    
    cat > "$output_dir/README.md" << EOF
# Analysis Report: $repo_name

**Generated**: $(date)
**Repository**: $repo_url

## 📊 Contents

- \`analysis.json\` — Full repository structure analysis
- \`diagram.mmd\` — Architecture diagram (Mermaid format)
- \`summary.json\` — AI-powered insights and hotspots
- \`ci_template.yml\` — Generated CI/CD workflow
- \`README.md\` — This file

## 🎨 Architecture Diagram

\`\`\`mermaid
$(cat "$output_dir/diagram.mmd" 2>/dev/null || echo 'graph LR\n  A[Diagram not available]')
\`\`\`

## 📝 Analysis Summary

\`\`\`json
$(cat "$output_dir/analysis.json" 2>/dev/null | head -20)
\`\`\`

See \`analysis.json\` for full details.

## 🤖 AI Insights

\`\`\`json
$(cat "$output_dir/summary.json" 2>/dev/null || echo '{"status": "summary_not_available"}')
\`\`\`

## 🔧 Generated CI/CD

\`\`\`yaml
$(head -20 "$output_dir/ci_template.yml" 2>/dev/null)
\`\`\`

See \`ci_template.yml\` for full template.

---

**Generated by RepoArchitectAgent**
EOF
    
    log_success "Report created: $output_dir/README.md"
}

# Main script
main() {
    clear
    echo -e "${BLUE}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║       RepoArchitectAgent - Demo Runs & Artifacts           ║"
    echo "║                        Step 13                             ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    
    # Check prerequisites
    log_info "Checking prerequisites..."
    
    if ! command -v python &> /dev/null; then
        log_error "Python not found. Install Python 3.11+ and try again."
        exit 1
    fi
    log_success "Python: $(python --version)"
    
    if ! command -v node &> /dev/null; then
        log_error "Node.js not found. Install Node.js 18+ and try again."
        exit 1
    fi
    log_success "Node.js: $(node --version)"
    
    if ! command -v git &> /dev/null; then
        log_error "Git not found. Install Git and try again."
        exit 1
    fi
    log_success "Git: $(git --version)"
    
    # Create demo directory
    mkdir -p "$RUN_DIR"
    log_success "Demo directory: $RUN_DIR"
    
    echo ""
    log_info "Starting demo runs..."
    echo ""
    
    # Demo 1: This repo (RepoArchitectAgent)
    run_analysis "https://github.com/$(git -C "$PROJECT_ROOT" remote get-url origin | sed 's/.*://' | sed 's/.git$//')" || log_warn "Failed to analyze primary repo"
    
    # Demo 2: Sample public repo (small)
    log_info "Running demo on sample public repository..."
    run_analysis "https://github.com/torvalds/linux" || log_warn "Failed to analyze Linux repo"
    
    # Demo 3: Another sample repo
    log_info "Running demo on another sample repository..."
    run_analysis "https://github.com/facebook/react" || log_warn "Failed to analyze React repo"
    
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                  Demo Complete! ✅                          ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    
    echo ""
    log_success "All artifacts saved to: $RUN_DIR"
    echo ""
    echo "📁 Directory structure:"
    ls -lah "$RUN_DIR"
    
    echo ""
    echo "📊 Artifacts available:"
    find "$RUN_DIR" -type f -name "*.json" -o -name "*.mmd" -o -name "*.yml" -o -name "*.md" | sed "s|^|  - |g"
    
    echo ""
    echo "🔗 View results:"
    echo "  cd $RUN_DIR"
    echo "  ls -la"
    echo ""
}

# Run main
main "$@"
